spring:
  application:
    name: prom-grafana
  jpa:
    database: POSTGRESQL
  datasource:
    url:
    username: ramanuj
    password: prom@6321P #incorrect sample password, use your own - Ramanuj :)
    driverClassName: org.postgresql.Driver
  sql:
    init:
      platform: postgres

server:
  port: 8080
  servlet:
    context-path: /

management:
  prometheus:
    metrics:
      export:
        enabled: true
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    prometheus:
      enabled: true
