CREATE TABLE customer_records (
                                  id SERIAL PRIMARY KEY,
                                  account_created_date TIMESTAMP,
                                  account_last_updated TIMESTAMP,
                                  account_lock_reason VARCHAR(255),
                                  account_locked BOOLEAN,
                                  account_manager_id BIGINT,
                                  account_status VARCHAR(50),
                                  account_unlock_date TIMESTAMP,
                                  address_line1 VARCHAR(255),
                                  address_line2 VARCHAR(255),
                                  annual_income DECIMAL(15, 2),
                                  average_cancellation_value DECIMAL(15, 2),
                                  average_cart_value DECIMAL(15, 2),
                                  average_discount_rate DECIMAL(5, 2),
                                  average_order_time BIGINT, -- Changed to BIGINT
                                  average_order_value DECIMAL(15, 2),
                                  average_purchase_frequency DECIMAL(5, 2),
                                  average_response_satisfaction_score DECIMAL(5, 2),
                                  average_response_time BIGINT, -- Assuming this is also in seconds
                                  average_return_value DECIMAL(15, 2),
                                  average_review_rating DECIMAL(5, 2),
                                  average_shipping_time BIGINT, -- Assuming this is also in seconds
                                  average_ticket_resolution_time BIGINT, -- Assuming this is also in seconds
                                  cart_abandonment_rate DECIMAL(5, 2),
                                  cart_conversion_rate DECIMAL(5, 2),
                                  churn_prediction_score DECIMAL(5, 2),
                                  city VARCHAR(255),
                                  contract_end_date TIMESTAMP,
                                  contract_renewal_date TIMESTAMP,
                                  contract_start_date TIMESTAMP,
                                  contract_value DECIMAL(15, 2),
                                  country VARCHAR(100),
                                  credit_score DECIMAL(5, 2),
                                  customer_segment VARCHAR(100),
                                  customer_since TIMESTAMP,
                                  customer_tier VARCHAR(50),
                                  date_of_birth DATE,
                                  delivery_failure_rate DECIMAL(5, 2),
                                  delivery_success_rate DECIMAL(5, 2),
                                  email VARCHAR(255),
                                  email_verified BOOLEAN,
                                  emergency_contact_name VARCHAR(255),
                                  emergency_contact_phone VARCHAR(20),
                                  emergency_contact_relationship VARCHAR(50),
                                  failed_login_attempts INT,
                                  favorite_product_category VARCHAR(100),
                                  first_name VARCHAR(100),
                                  fraud_alert BOOLEAN,
                                  gender VARCHAR(10),
                                  highest_order_value DECIMAL(15, 2),
                                  in_app_notifications_opt_in BOOLEAN,
                                  last_cart_item_added_date TIMESTAMP,
                                  last_login TIMESTAMP,
                                  last_login_ip VARCHAR(45),
                                  last_name VARCHAR(100),
                                  last_password_change_date TIMESTAMP,
                                  last_password_change_ip VARCHAR(45),
                                  last_purchase_date TIMESTAMP,
                                  last_ticket_date TIMESTAMP,
                                  last_updated_by_system TIMESTAMP,
                                  last_updated_by_user TIMESTAMP,
                                  last_wishlist_item_added_date TIMESTAMP,
                                  lifetime_value DECIMAL(15, 2),
                                  loyalty_points BIGINT,
                                  loyalty_program_id BIGINT,
                                  marital_status VARCHAR(20),
                                  marketing_opt_in BOOLEAN,
                                  marketing_segment VARCHAR(100),
                                  most_purchased_product_category VARCHAR(100),
                                  net_promoter_score DECIMAL(5, 2),
                                  newsletter_subscribed BOOLEAN,
                                  number_of_cancellations INT,
                                  number_of_children INT,
                                  number_of_logins INT,
                                  number_of_orders INT,
                                  number_of_promo_codes_used INT,
                                  number_of_returns INT,
                                  occupation VARCHAR(100),
                                  password_hash VARCHAR(255),
                                  password_last_reset TIMESTAMP,
                                  payment_failure_rate DECIMAL(5, 2),
                                  payment_method_1 VARCHAR(50),
                                  payment_method_1_details TEXT,
                                  payment_method_2 VARCHAR(50),
                                  payment_method_2_details TEXT,
                                  payment_method_3 VARCHAR(50),
                                  payment_method_3_details TEXT,
                                  payment_success_rate DECIMAL(5, 2),
                                  phone_number VARCHAR(20),
                                  phone_verified BOOLEAN,
                                  preferred_billing_address VARCHAR(255),
                                  preferred_contact_method VARCHAR(50),
                                  preferred_contact_time VARCHAR(50),
                                  preferred_currency VARCHAR(3),
                                  preferred_language VARCHAR(20),
                                  preferred_shipping_address VARCHAR(255),
                                  product_review_count INT,
                                  referral_conversion_rate DECIMAL(5, 2),
                                  referred_by_customer_id BIGINT,
                                  registered_ip VARCHAR(45),
                                  risk_score DECIMAL(5, 2),
                                  sales_region VARCHAR(100),
                                  sales_representative_id BIGINT,
                                  security_answer_1 VARCHAR(255),
                                  security_answer_2 VARCHAR(255),
                                  security_answer_3 VARCHAR(255),
                                  security_question_1 VARCHAR(255),
                                  security_question_2 VARCHAR(255),
                                  security_question_3 VARCHAR(255),
                                  sms_notifications_opt_in BOOLEAN,
                                  social_media_login_id VARCHAR(255),
                                  social_media_login_provider VARCHAR(50),
                                  state VARCHAR(50),
                                  subscription_end_date TIMESTAMP,
                                  subscription_plan_id BIGINT,
                                  subscription_start_date TIMESTAMP,
                                  subscription_status VARCHAR(50),
                                  support_ticket_count INT,
                                  timezone VARCHAR(50),
                                  total_discount_value DECIMAL(15, 2),
                                  total_purchase_value DECIMAL(15, 2),
                                  total_referrals INT,
                                  total_shipping_cost DECIMAL(15, 2),
                                  two_factor_enabled BOOLEAN,
                                  two_factor_method VARCHAR(50),
                                  wish_list_item_count INT,
                                  zip_code VARCHAR(20)
);
